
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class CollegeInfo extends javax.swing.JFrame {
String scholorshipStatus = "";

    
    /**
     * Creates new form CollegeInfo
     */
    public CollegeInfo() {
        initComponents();
        importData();
        
        
         
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scholarshipBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        demonstrationTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        collegeId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        collegeName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        catagory = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        collegeCourse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        affiliation = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sAvailable = new javax.swing.JRadioButton();
        sUnavailable = new javax.swing.JRadioButton();
        register = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        feeTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        catagoryCb = new javax.swing.JComboBox<>();
        searchCollege = new javax.swing.JButton();
        searchFee = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        importBtn = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("College Information System");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("College Information System");

        demonstrationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Catagory", "Course", "Affiliation", "Fee", "Scholarship"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(demonstrationTable);
        if (demonstrationTable.getColumnModel().getColumnCount() > 0) {
            demonstrationTable.getColumnModel().getColumn(0).setResizable(false);
            demonstrationTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            demonstrationTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            demonstrationTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            demonstrationTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            demonstrationTable.getColumnModel().getColumn(5).setResizable(false);
            demonstrationTable.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register College", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("College ID");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("College Name");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Catagory");

        catagory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Community College", "Junior College", "Women's College", "Technical Institute", "Professional School" }));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Course");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Affiliation");

        affiliation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pokhara University", "Purvanchal University", "Kathmandu University", "Tribhuvan University" }));

        jLabel6.setText("Price");

        jLabel7.setText("Scholarship");

        scholarshipBtnGroup.add(sAvailable);
        sAvailable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        sAvailable.setText("Available");

        scholarshipBtnGroup.add(sUnavailable);
        sUnavailable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        sUnavailable.setText("Unavailable");

        register.setBackground(new java.awt.Color(51, 153, 255));
        register.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(register)
                                .addComponent(sUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(affiliation, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(collegeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(catagory, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(collegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(collegeId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(collegeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(collegeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(catagory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(collegeCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(affiliation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAvailable)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sUnavailable)
                .addGap(26, 26, 26)
                .addComponent(register)
                .addGap(114, 114, 114))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 12))); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("Search By Price:");

        jLabel10.setText("Fee");

        feeTf.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        feeTf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setText("Search By Catagory:");

        jLabel13.setText("Catagory");

        catagoryCb.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        catagoryCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Community College", "Technical Institute", "Professional School", "Women's College", "Jounior College" }));

        searchCollege.setBackground(new java.awt.Color(51, 153, 255));
        searchCollege.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        searchCollege.setForeground(new java.awt.Color(255, 255, 255));
        searchCollege.setText("Search Catagory");
        searchCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCollegeActionPerformed(evt);
            }
        });

        searchFee.setBackground(new java.awt.Color(51, 153, 255));
        searchFee.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        searchFee.setForeground(new java.awt.Color(255, 255, 255));
        searchFee.setText("Search Fee");
        searchFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchFee)
                            .addComponent(feeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(107, 107, 107)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchCollege)
                            .addComponent(catagoryCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(feeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(catagoryCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCollege)
                    .addComponent(searchFee))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(310, 310, 310))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        importBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        importBtn.setText("Import");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });
        jMenu1.add(importBtn);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private int [] selectionSort(int [] a ){
        for (int i = 0 ; i < a.length - 1; i++){
        int min = minimumPosition(a,i);
        swap(a,min,i);
       
        
    }
      return a;  
    }
    
    private int minimumPosition(int [] a , int from){
        int min = from;
        for (int i = from + 1  ; i < a.length ; i++){
            if(a[i] < a[min]){
                min = i;
                
            }
        }
        
        return min;
    }

    private void swap(int[] a, int i, int j) {
        int temp = a[i];
        a[i] = a[j];
        a[j] = temp;
      
    }
    
    
    
    public static int binarySearch(int [] a, int key){
        
       
         int low = 0;
         int high = a.length - 1 ;
         while(low <= high){
             int mid = (low + high )/ 2;
             
             if (a[mid]== key){
                 return mid;
             }
             else if( a[mid] <key){
                 low = mid + 1;
             }
             else{
                 high = mid -1;
             }
             
         }
          return -1;
    }
    
    
     private void removeContent(){
        
        DefaultTableModel dm = (DefaultTableModel)  demonstrationTable.getModel();
        int i =  0 ;
        
        do{
            
            dm.removeRow(i);
        }while(i<dm.getRowCount());
        
    }
        
     private void importData(){
          String path = "data.txt";
         
         File file = new File(path);
         BufferedReader br;
         
         try (FileReader fr = new FileReader(file)) {
             br = new BufferedReader(fr);
             DefaultTableModel model = (DefaultTableModel) demonstrationTable.getModel();
             Object[] lines = br.lines().toArray();
                   
             for (Object line : lines) {
                String[] row = line.toString().split("\t");
                model.addRow(row);
                br.close();
              }
         } catch (FileNotFoundException ex) {
            Logger.getLogger(CollegeInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CollegeInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void dataExport(){
    
          try
        {
            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter("data.txt", true));
            

            bufferedWriter.write("");
           
            
            
            bufferedWriter.write(collegeId.getText());
            bufferedWriter.write("\t");
            bufferedWriter.write(collegeName.getText());
            bufferedWriter.write("\t");
            bufferedWriter.write(catagory.getSelectedItem().toString());
            bufferedWriter.write("\t");
            bufferedWriter.write(collegeCourse.getText());
            bufferedWriter.write("\t");
            bufferedWriter.write(affiliation.getSelectedItem().toString());
            bufferedWriter.write("\t");
            bufferedWriter.write(price.getText());
            bufferedWriter.write("\t");
            bufferedWriter.write(scholorshipStatus);
            bufferedWriter.write("\n");
            bufferedWriter.close();
            
            reset();
            
            
        }catch(Exception ex)
        {
           ex.printStackTrace();
        }
        
    }
    
    private void reset(){
            collegeId.setText("");
            collegeName.setText("");
            collegeCourse.setText("");
            price.setText("");
            scholarshipBtnGroup.clearSelection();
        
    }
    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // For Displaying the data filled in the form in the table:
        
        
        if(sAvailable.isSelected()) {
            scholorshipStatus = sAvailable.getText();
        }
        else if(sUnavailable.isSelected()){
            scholorshipStatus = sUnavailable.getText();
        }
       
        
        if (collegeId.getText().isEmpty() || collegeName.getText().isEmpty() || catagory.getSelectedItem().toString().isEmpty() ||
         collegeCourse.getText().isEmpty() || affiliation.getSelectedItem().toString().isEmpty() || price.getText().isEmpty() || scholorshipStatus.equals("")){
            
            JOptionPane.showMessageDialog(rootPane, "All fields must be filled");
            reset();
        }
        else if(collegeId.getText() != ""){
            checkId();
        }
        
        else{
     
            DefaultTableModel model = (DefaultTableModel) demonstrationTable.getModel();
            model.addRow(new Object[] {collegeId.getText(),collegeName.getText(),catagory.getSelectedItem(),
            collegeCourse.getText(), affiliation.getSelectedItem(),  price.getText(),scholorshipStatus});
        
            JOptionPane.showMessageDialog(null, "Data Successfully stored in memory.");
        
            dataExport();
            reset();
            
        }
        
        
       
    }//GEN-LAST:event_registerActionPerformed
     
    private void checkId(){
        int rows = demonstrationTable.getRowCount();
        
        int [] id = new int[rows];
        
        for(int i = 0 ; i< rows ; i++){
             
             id [i] = Integer.parseInt(demonstrationTable.getValueAt(i,0).toString());
         }
        
        int inputId = Integer.parseInt(collegeId.getText().toString());
        
        for(int i = 0; i<rows; i++){
                 if(id[i]== inputId){
                     JOptionPane.showMessageDialog(rootPane, " The id is already registered. \n Please enter another id.");
                     reset();
                 }
        }
        
    }
    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        // checking if the 
        
        if(demonstrationTable.getRowCount() == 0){
            importData();
        }else{
            removeContent();
            importData();
        }
                
    }//GEN-LAST:event_importBtnActionPerformed

    private void searchFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFeeActionPerformed
        // TODO add your handling code here:
        if(feeTf.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, " Please enter the price value ! ");
        }
        DefaultTableModel table = (DefaultTableModel) demonstrationTable.getModel();
        
        int rows = demonstrationTable.getRowCount();
        
        int [] priceOfColleges = new int[rows];
        
         for(int i = 0 ; i< rows ; i++){
             
             priceOfColleges[i] = Integer.parseInt(demonstrationTable.getValueAt(i,5).toString());
         }
         
         int sortedPriceOfColleges [] = selectionSort(priceOfColleges);
         
         int userInput = Integer.parseInt(feeTf.getText());
         
         int searchIndex = binarySearch(sortedPriceOfColleges,userInput);
         
         if (searchIndex != -1){
             
             for(int i = 0; i<rows; i++){
                 if(Integer.parseInt(demonstrationTable.getValueAt(i,5).toString())== sortedPriceOfColleges[searchIndex]){
                     JOptionPane.showMessageDialog(rootPane, "The information about the college that was found is as follows: \nCollege Id : "+
                             table.getValueAt(i,0)+"\nCollege Name : "+ table.getValueAt(i, 1)+"\nCatagory : "+table.getValueAt(i,2)
                             +"\nCourse : "+table.getValueAt(i, 3) + "\nAffiliation : " + table.getValueAt(i,4) + "\nPrice : " + table.getValueAt(i,5) 
                             + "\nScholorship : " + table.getValueAt(i,6));
                      
                 }
             }
             
         }else
             JOptionPane.showMessageDialog(rootPane, "No college matched the input fee");
        
        
    }//GEN-LAST:event_searchFeeActionPerformed
    
    private void searchCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCollegeActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel table = (DefaultTableModel) demonstrationTable.getModel();
        String userInput = catagoryCb.getSelectedItem().toString();
        
        ArrayList <String> output = new ArrayList<>();
        
        int rows = demonstrationTable.getRowCount();
        
        
        for(int i = 0 ; i< rows ; i++){
            if (demonstrationTable.getValueAt(i, 2).toString().equals(userInput)){
                output.add(demonstrationTable.getValueAt(i, 1).toString());
            }
        }
        
        
        if(output.isEmpty()){
            JOptionPane.showMessageDialog(rootPane," No colleges found ! ");
        }else{
            String collegesName ="";
            int index = 0;
            
            do{
               collegesName = collegesName + output.get(index) + " , " ;
               index ++;
            }while(index<output.size());
            JOptionPane.showMessageDialog(rootPane,"There are "+ output.size()+ " colleges : " + collegesName);
        }
        
    }//GEN-LAST:event_searchCollegeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollegeInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollegeInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> affiliation;
    private javax.swing.JComboBox<String> catagory;
    private javax.swing.JComboBox<String> catagoryCb;
    private javax.swing.JTextField collegeCourse;
    private javax.swing.JTextField collegeId;
    private javax.swing.JTextField collegeName;
    private javax.swing.JTable demonstrationTable;
    private javax.swing.JTextField feeTf;
    private javax.swing.JMenuItem importBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JButton register;
    private javax.swing.JRadioButton sAvailable;
    private javax.swing.JRadioButton sUnavailable;
    private javax.swing.ButtonGroup scholarshipBtnGroup;
    private javax.swing.JButton searchCollege;
    private javax.swing.JButton searchFee;
    // End of variables declaration//GEN-END:variables
}
